name: Craftweg

on:
  push:
    branches:
      - main
  pull_request: {}

env:
  NODE_VERSION: '16.13.0'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '${{ env.NODE_VERSION }}'
          cache: 'npm'
      - name: Install dependencies
        run: |
          npm install
      - name: Build
        run: |
          npm run build
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '${{ env.NODE_VERSION }}'
          cache: 'npm'
      - name: Install dependencies
        run: |
          npm install
      - name: Check
        run: |
          npm run check
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '${{ env.NODE_VERSION }}'
          cache: 'npm'
      - name: Install dependencies
        run: |
          npm install
      - name: Lint
        run: |
          npm run lint
