name: ppinera.es

on:
  push:
    branches:
      - main
  pull_request: {}

env:
  NODE_VERSION: '16.13.0'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '${{ env.NODE_VERSION }}'
          cache: 'npm'
      - name: Install dependencies
        run: |
          npm install
      - name: Build
        run: |
          npm run build